### ISSUE TITLE
IMPORTANTE: Las gráficas no se guardan

### ISSUE THREAD

**Issue by Marbelaezl** [Marbelaezl/ProyectoHPC#1]
En 3dplot.py, las gráficas correspondientes se muestran pero al intentar guardarlas, sale un archivo en blanco. Es posible que la función usada (plt.savefig("nombre.png/pdf")) no sea la correcta, pero no estoy seguro de qué lo causa

**Comment by anprietoa** [comment]
ya funciona, plt.show() debia estar despues de plt.savefig
